### ISSUE TITLE
Non-terminal divergence between parser and macro matcher 

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/lang-team#111]
# Summary

Spawned off of https://github.com/rust-lang/rust/issues/86730 (which in turn was spawned off of https://github.com/rust-lang/rust/pull/84364 and [previous lang team meetings](https://github.com/rust-lang/lang-team/blob/master/minutes/2021-05-11.md#add-expr202x-macro-pattern-rust84364))

The meaning of non-terminals such as "expr" according to the rustc parser have changed (or would like to change) from its meaning according to the current rustc macro matcher. Each time this happens, we have to decide what to do about it (e.g. whether to add a new macro fragment specifier, such as `expr202x`).

The main topic to discuss is what to do about `expr` itself, in the short term. (There is a side-topic of how we should try to manage future changes on this front. Answers here might be a broad as changing the macro system itself, but that in turn means it may need its own design meeting...)

# Background reading

pnkfelix plans to produce a document that folks will be able to consume at the meeting itself.

The main background material available now is linked from https://github.com/rust-lang/rust/issues/86730

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by pnkfelix** [comment]
meeting scheduled for 2021-08-25

**Comment by nikomatsakis** [comment]
I don't think we're doing this meeting :)
