### ISSUE TITLE
Prototype Sync & Async Iterator Items (Minimal generators)

### ISSUE THREAD

**Issue by estebank** [rust-lang/lang-team#121]
# Proposal

## Summary and problem statement

 - I want to introduce a new nightly-only way to express sync and async iterator combinators through new syntax.

## Motivation, use-cases, and solution sketches

This feature is the underlying mechanism behind `async`/`await` state machines,
and has been available to use on the nighlty channel for 4 years now. The lack
of stable generators burdens users' with the need to implement `Iterator`s and
`AsyncIterator`s (`Stream`s) combinators by hand, which can be difficult,
particularly when it comes to `AsyncIterator`s due to the need to understand
`Pin` in order to be productive, which is a common source of confusion amongst
users. As part of the Async Vision document, `Pin` and manually implemented
combinators have been identified as a common source of frustration. Generators
are a common feature available in languages like C#, JS and Python. Stabilizing
this feature would be a huge boon to productivity and make significant
improvement in the ease of use of `async`/`await`.

`std::iter::from_fn` is available, which removes *some* of the need for a full blown feature, but it is very limited. Currently there are three proc-macro crates that can be used to mimic the proposed behavior: gen-iter, Propane and async-stream.

Generators are "unnameable types" that conform to the unstable `Generator`
trait, similar to closures and the `Fn*()`-family of traits. We do *not* propose
to stabilize the `Generator` trait, but make it trivial to use the resulting
generator anywhere an `Iterator` or `AsyncIterator` is accepted.

There are multiple open questions at this time that require experimentation:

 - How to deal with "specialization" of behavior (namely, allowing an iterator item that implements DoubleEndedIterator when possible)
 - How to programmatically or syntactically allow for `size_hint`
 - For `AsyncIterator`, should the entire iterator be `Pin`?

## Links and related work

 - [Sync and Async Iterator Items, AKA Minimal Generators - Lang Team meeting conversation](https://hackmd.io/9v81TQSgQcaAiqvHQtzN8w)
 - [Async Iterators Semantics Draft RFC](https://github.com/estebank/rfcs/blob/stable-generators/text/0000-generators.md)
 - [Async Iterators Syntax Draft RFC](https://github.com/estebank/rfcs/blob/stable-generators/text/0000-stable-generator-syntax.md)
 - [generators - Unstable Book](https://doc.rust-lang.org/beta/unstable-book/language-features/generators.html)
 - [tracking issue](https://github.com/rust-lang/rust/issues/43122)
 - [original generators RFC](https://github.com/rust-lang/rfcs/blob/master/text/2033-experimental-coroutines.md)
 - Prior art: [Python](https://wiki.python.org/moin/Generators), [C#](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/yield)

## Initial people involved

- Owner: @estebank
- Liaison: TBD

## What happens now?

This issue is part of the lang-team [initiative process]. Once this issue is filed, a Zulip topic will be opened for discussion, and the lang-team will review open proposals in its weekly triage meetings. You should receive feedback within a week or two.

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[forge]: https://forge.rust-lang.org/
[initiative process]: https://lang-team.rust-lang.org/initiatives.html

**Comment by nikomatsakis** [comment]
I've opened the issue #137 to track this (accepted) initiative.
