### ISSUE TITLE
Lint policy

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#132]
# Summary

Discuss overall policy on where we expect lints/warnings/etc.

Goal of the meeting is to enumerate what kinds of things would be in the policy and to review state we reached around Rust 2021 edition.

# Background reading

*Include any links to material that folks ought to try to read before-hand.*

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by nikomatsakis** [comment]
cc @rylev

**Comment by nikomatsakis** [comment]
Scheduled for Mar 30, @pnkfelix to prepare

**Comment by pnkfelix** [comment]
This meeting took place on 2022-03-30, as scheduled. 

Here is the doc that we used to drive the meeting ( including [Meeting Notes](https://hackmd.io/PJGrfKGEQ_qNvW_BMtfR8A?view#Meeting-Notes-dequeued) at the end of the doc): https://hackmd.io/PJGrfKGEQ_qNvW_BMtfR8A

**Comment by pnkfelix** [comment]
Meeting notes are up as https://github.com/rust-lang/lang-team/pull/157 ; once that is merged, we should close this issue.
