### ISSUE TITLE
Plan for enum discrim, repr, and casting

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/lang-team#134]
# Summary

We have long-standing open issues regarding how/whether one can cast an enum to its discriminant value.

We have found when touching on this topic in the triage meetings that we need a dedicated design meeting to better understand the status quo, where we might go next, and where we *want* to go.

@jswrenn will work with @pnkfelix on making a document to drive the meeting.

# Background reading

https://github.com/rust-lang/rust/pull/88203

https://github.com/rust-lang/rust/issues/60553#issuecomment-984290718

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by nikomatsakis** [comment]
Re-open if still relevant
