### ISSUE TITLE
A path towards stable generic const expressions

### ISSUE THREAD

**Issue by lcnr** [rust-lang/lang-team#138]
# Summary

@rust-lang/project-const-generics recently started the [discussion about](https://rust-lang.zulipchat.com/#narrow/stream/260443-project-const-generics/topic/.60min_generic_const_exprs.60) - and experimental implementation of - `feature(min_generic_const_expr)`. In short, this will extend const arguments to also support generic named constants and will hopefully be far easier to stabilize than the current design of `feature(generic_const_exprs)`.

With this, computations as const arguments are finally possible. Any further extension to which generic const arguments are allowed do **not** enable any new behavior and will therefore mostly reduce noise for the user.

For this to be usable, we intend to also work towards implementing and stabilizing generic free constants and generic associated constants, adding the ability to define generic parameter and add where-clauses to named constants.

## Examples
```rust
// A generic free constant:
const ADD<const N: usize, const M: usize> = N + M;
// A function using that generic free constant in a type/array length.
fn push<T, const N: usize>(arr: [T, N], value: T) -> [T; ADD::<N, 1>] {
    // ...
}

// Using generic const expressions is still not supported, so this will error!
fn push<T, const N: usize>(arr: [T, N], value: T) -> [T; N + 1] {
    // ...
}
```

# Background reading

https://lcnr.de/blog/generic-const-expressions/

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by nikomatsakis** [comment]
Oh, lol. Well, i'd be game to second this -- but I guess we don't need a "new initiative" around it.

**Comment by lcnr** [comment]
closing this as I am currently taking a deeper dive into the needs and implementation options here.
