### ISSUE TITLE
Add const evaluatable `where const { <block> }`

### ISSUE THREAD

**Issue by JulianKnodt** [rust-lang/lang-team#163]
# Proposal

Currently, the type system supports type-level equalities through the use of Peano numbers and type-level booleans. Thus, it's possible to be able to gate certain functions to integers at compile-time using type-level shenanigans, but this makes it difficult to build readable APIs. Thus, there has been a long-time suggestion to have `where` blocks that allow for const evaluatable expressions such as `where { N > 2 }`, that would essentially be syntactic sugar. They would be much easier to write than type-level expressions. 

It would be the most convenient to integrate these directly with existing syntax. Thus, it would be best to simple make these blocks identical to [`const { }`](https://github.com/rust-lang/rust/issues/76001). One key difference is that it would seem crucial that these const blocks would be populated with the const-generic parameters of the enclosing environment, which would differ from existing inline-consts (I believe). Specifically the final syntax would look like:

```
fn example<const N: usize, M: u32>() -> () where const { N == 3 }, const { N < (M as usize) } {
    ()
}
```

## Motivation, use-cases, and solution sketches

This is specifically trying to solve the problem of having unreadable const APIs, as well as having to mangle with the type system to get compile time bounds. I'm not sure if that inline-consts are complete, but if so the main component would be adding in a ProjectionBound for consts that checks that it evaluates to true before compilation.

## Links and related work

While I'm not aware of any specific const block in a language, the [Eiffel](https://www.eiffel.org/doc/eiffelstudio/Precondition) programming language has preconditions, which can be thought of as conceptually similar except this is at compile time.

## Initial people involved

I'm planning on working on this myself.

## What happens now?

This issue is part of the lang-team [initiative process]. Once this issue is filed, a Zulip topic will be opened for discussion, and the lang-team will review open proposals in its weekly triage meetings. You should receive feedback within a week or two.

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[forge]: https://forge.rust-lang.org/
[initiative process]: https://lang-team.rust-lang.org/initiatives.html

**Comment by JulianKnodt** [comment]
That's definitely fair, but I think it's not clear to me exactly whether there would need to be divergent behavior between inline-consts in a where block, or those inside of a function. Could they be exactly the same, or is it that they would need to be handled slightly differently?

**Comment by safinaskar** [comment]
Please, don't use `as`. `as` in its current form is very bad. For example, `as` silently truncates numbers in all compilation modes!
