### ISSUE TITLE
add `#[never_call]` attribute

### ISSUE THREAD

**Issue by sahandevs** [rust-lang/lang-team#170]
# Proposal

## Summary and problem statement

This macro is useful for library authors, mostly code generators.
Basically, by putting `#[never_call]` over a function we mark it as __uncallable__ and calling it causes a compiler error. Example:
```rust
#[never_call]
fn never_call_me() { }

fn main() {
  never_call_me();
}
```
output:
```
error[E01XX]: call to a function with #[never_call] attribute
   --> src/main.rs:160:5
    |
160 |     never_call_me();
    |     ^^^^^^^^^^^^^^^ can't use this function
    |
    = note: this function cannot be called
```
We can also specify the reason by giving the macro the optional `reason` argument. Example:
```rust
#[never_call(reason="my reason")]
fn never_call_me() { }

fn main() {
  never_call_me();
}
```
output:
```
error[E01XX]: call to a function with #[never_call] attribute
   --> src/main.rs:160:5
    |
160 |     never_call_me();
    |     ^^^^^^^^^^^^^^^ can't use this function
    |
    = reason: my reason
```

## Motivation, use-cases, and solution sketches

[`tidy-builder`](https://github.com/maminrayej/tidy-builder) is a crate that provides compile-time safe builder patterns. Given following struct:

```rust
pub struct Item {
    pub a: usize,
    pub b: Option<usize>,
    pub c: usize,
    pub d: Option<usize>,
    pub e: Option<usize>,
    pub f: usize,
}
```
it generates this code:

<details>
<summary>Generated Code</summary>

```rust

pub mod ItemBuilder {
    pub struct ItemBuilder<const A_SET: bool, const C_SET: bool, const F_SET: bool> {
        a: Option<usize>,
        b: Option<usize>,
        c: Option<usize>,
        d: Option<usize>,
        e: Option<usize>,
        f: Option<usize>,
    }
    
    pub fn new() -> ItemBuilder<false, false, false> {
        ItemBuilder { a: None, b: None, c: None, d: None, e: None, f: None }
    }
    
    impl<const A: bool, const B: bool, const F: bool> ItemBuilder<A, B, F> {
    
        pub fn a(self, value: usize) -> ItemBuilder<true, B, F> {
            ItemBuilder {
                a: Some(value),
                b: self.b,
                c: self.c,
                d: self.d,
                e: self.e,
                f: self.f,
            }
        }
    
        pub fn b(mut self, value: usize) -> Self {
            self.b = Some(value);
            self
        }
        
        pub fn c(self, value: usize) -> ItemBuilder<A, true, F> {
            ItemBuilder {
                a: self.a,
                b: self.b,
                c: Some(value),
                d: self.d,
                e: self.e,
                f: self.f,
            }
        }
    
        pub fn d(mut self, value: usize) -> Self {
            self.d = Some(value);
            self
        }
    
        pub fn e(mut self, value: usize) -> Self {
            self.e = Some(value);
            self
        }
    
        pub fn f(self, value: usize) -> ItemBuilder<A, B, true> {
            ItemBuilder {
                a: self.a,
                b: self.b,
                c: self.c,
                d: self.d,
                e: self.e,
                f: Some(value),
            }
        }
    }
    
    impl ItemBuilder<true, true, true> {
        pub fn build(self) -> super::Item {
            unsafe {
                super::Item {
                    a: self.a.unwrap_unchecked(),
                    b: self.b,
                    c: self.c.unwrap_unchecked(),
                    d: self.d,
                    e: self.e,
                    f: self.f.unwrap_unchecked(),
                }
            }
        }
    }
} 

fn test() {
    let builder = ItemBuilder::new()
        .a(1)
        .c(3)
        .a(3)
        .f(4)
        .a(1)
        .build();
}
```

</details>

the `build()` method is not available unless we provide all the required fields. The problem is when using the build method while not all the required fields are given, the error message becomes unclear:

```
error[E0599]: no method named `build` found for struct `MyStructBuilder<true, false>` in the current scope
  --> tests/ui/no_generics.rs:12:10
   |
1  | #[derive(tidy_builder::Builder)]
   |          --------------------- method `build` not found for this
...
12 |         .build();
   |          ^^^^^ method not found in `MyStructBuilder<true, false>`
   |
   = note: the method was found for
           - `MyStructBuilder<true, true>`
```

the goal of this proposal is to provide a way for library authors to generate some compile errors in this kind of situations.

## Links and related work

alternative work arounds are being discussed here: https://github.com/maminrayej/tidy-builder/issues/2

## What happens now?

This issue is part of the lang-team [initiative process]. Once this issue is filed, a Zulip topic will be opened for discussion, and the lang-team will review open proposals in its weekly triage meetings. You should receive feedback within a week or two.

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[forge]: https://forge.rust-lang.org/
[initiative process]: https://lang-team.rust-lang.org/initiatives.html

**Comment by nikomatsakis** [comment]
I'm going to close this issue since we've revised our initiative process and are phasing our MCPs. Viable next steps at this point are either to prepare an [in-tree experiment](https://lang-team.rust-lang.org/how_to/experiment.html) (if there is an experienced Rust developer and a lang-team member willing to serve as liaison) or to [start drafting an RFC](https://lang-team.rust-lang.org/how_to/propose.html). This particular change seems small enough that an RFC is likely the next best step, but it'd be good to identify someone on lang team who wants to push it through regardless.
