### ISSUE TITLE
Review const evaluation skill-tree and unsafe questions

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#18]
# Meeting proposal info

- **Title:** Const evaluation skill-tree 
- **Type:** technical
  
# Summary

We should discuss the work that @oli-obk did to prepare a const evaluation roadmap. I'd also like to talk about the definition of unsafe in const functions. Do they both fit in one meeting? We could narrow the topic down.

Background reading:

* Const evaluation skill-tree from https://github.com/rust-lang/const-eval/pull/43
* [Thoughts on Compile-Time Function Evaluation and Type Systems](https://www.ralfj.de/blog/2018/07/19/const.html), blog post by @RalfJung 

Some other folks that may want to be involved:

* @RalfJung 
* @ecstatic-morse

# About this issue

This issue corresponds to a meeting proposal for the lang team design. It corresponds to a possible topic of discussion.

**Comment by RalfJung** [comment]
That's right in the middle of dinner time for me, so it's not great. :/  But I guess I could have later dinner.

**Comment by oli-obk** [comment]
works for me

**Comment by nikomatsakis** [comment]
I'm tentatively scheduling this for next week, July 24th. @RalfJung and @oli-obk hopefully that works for you?

**Comment by RalfJung** [comment]
You mean June 24th?

**Comment by nikomatsakis** [comment]
I did, but now it looks like we are going to move to July 1st, @RalfJung.

**Comment by RalfJung** [comment]
That week and the week after it are not great, I have two deadlines around there...

**Comment by nikomatsakis** [comment]
Oh sigh. =) Scheduling is hard.

**Comment by nikomatsakis** [comment]
I think we'll move it back then, just checking in on #26.

**Comment by nikomatsakis** [comment]
Now scheduled for June 24.

**Comment by RalfJung** [comment]
Noted, thanks :)
