### ISSUE TITLE
2023 roadmap update

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#188]
# Summary

* Read over last year's roadmap
* Think about what has been done, what still applies, what may not
* Draft a new blog post

# Background reading

https://blog.rust-lang.org/inside-rust/2022/04/04/lang-roadmap-2024.html

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by nikomatsakis** [comment]
Closing this for now

**Comment by WaffleLapkin** [comment]
What is the reason for closing this?
