### ISSUE TITLE
ffi-unwind

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#19]
## Summary

Working out the rules for cross-language unwinding as well as longjmp.

## Status

This section lists the efforts that we are working towards.

### "C-unwind" ABI

The "C-unwind" ABI allows you to invoke foreign functions that may unwind using the native ABI.

* Specification: rust-lang/rfcs#2945 has been merged. This RFC introduces the "C-unwind" ABI.
* Implementation: We are looking for someone to implement! The tracking issue for the implementation work is https://github.com/rust-lang/rust/issues/74990.

### Interaction with `catch_unwind`

We need to define what happens when foreign exceptions interact with `catch_unwind`.

### longjmp compatibility

We need to define the conditions in which it is legal to longjmp through Rust frames. We've done some initial conversation about this.

## Links

* [Repository](https://github.com/rust-lang/project-ffi-unwind)
* Zulip-stream: [`#project-ffi-unwind`](https://rust-lang.zulipchat.com/#narrow/stream/210922-project-ffi-unwind)

**Comment by nikomatsakis** [comment]
2020-04-02: Working towards RFC

**Comment by nikomatsakis** [comment]
2020-04-09: [BatmanAod opened a PR with draft of RFC](https://github.com/rust-lang/project-ffi-unwind/pull/28)

**Comment by nikomatsakis** [comment]
2020-04-30: 
    - The only question is whether to make it “defined behavior” if a foreign except propagates across a “C unwind” boundary (and there is no `catch_unwind`)
        - Advantage: we probably want to support this
        - Disadvantage: it will require a shim to catch C++ exceptions — this is probably necessary later, unless we reverse the “two ABIs” proposal
    - Interesting downside of the “two ABI” design
        - If you have a C function but it takes callbacks, then there could potentially be pressure to make callbacks into “C unwind” and the function too (for flexibility)
            - but note that this is not a trivial change, necessarily, and indeed many C libraries are not ready for this to happen “just because”
        - True, but just a downside of this approach.

**Comment by nikomatsakis** [comment]
2020-06-01:
    - Plain Old Frames — for frames that don’t have a pending destructor or `catch_unwind`

**Comment by nikomatsakis** [comment]
2020-06-11:

We uncovered a few interesting things in discussing the latest draft. The most important is that we are not comfortable saying that longjmp functions can unwind Plain Old Frames (POF) without any further annotation, because that will hinder our efforts to optimize. For the time being, we plan to edit the RFC to leave the details of when longjmp is legal as TBD, but we discussed some possible alternative proposals here https://github.com/rust-lang/project-ffi-unwind/issues/30.

**Comment by nikomatsakis** [comment]
2020-06-22:

* [RFC 2945 opened](https://github.com/rust-lang/rfcs/pull/2945)
* Not just about "C" vs "C unwind" ABIs, but we currently use `#[unwind(allowed)]` for `"system"`:

```rust
    extern "system" {
        #[unwind(allowed)]
        pub fn _CxxThrowException(pExceptionObject: *mut c_void, pThrowInfo: *mut u8) -> !;
    }
```

* Options:
    * add `"system unwind"`, `"stdcall unwind"`, etc
    * maybe `"system"` itself is redundant

**Comment by nikomatsakis** [comment]
2020-07-06:

* RFC is believed to be ready for FCP, needs someone from lang-team to review and fcp merge.
* We clarified that other ABIs (e.g., `system`) may have unwind variants (e.g., `extern "system unwind"`).

**Comment by nikomatsakis** [comment]
2020-07-20:

* RFC has just entered FCP.
* Bikeshedding now about "C unwind" vs "C-unwind"

**Comment by nikomatsakis** [comment]
2020-07-27:

* Bikeshed resolved ABI name to "C-unwind".

**Comment by nikomatsakis** [comment]
2020-07-31:

* rust-lang/rfcs#2945 is merged and tracking issue https://github.com/rust-lang/rust/issues/74990 is opened.

**Comment by nikomatsakis** [comment]
2020-09-14:

* Implementation work is ongoing, we may start looking at the longjmp question.

**Comment by nikomatsakis** [comment]
2020-09-21:

No update.

**Comment by joshtriplett** [comment]
Discussion in today's meeting:

- New discussion and proposals for handling "target ABI"
  - e.g. target for native iOS vs target for iOS simulator, which have different ABIs
  - Rust doesn't have a way to express this today

This isn't directly in the current ffi-unwind charter. Rather than expanding it (which we'd do to cover c++/longjmp/etc), we may need to consider chartering an additional project for new FFI issues.

**Comment by joshtriplett** [comment]
(Not sure why this unassigned @BatmanAoD.)

**Comment by nikomatsakis** [comment]
Update:

* @BatmanAoD plans to write a blog post setting the direction for work on functions that can be deallocated ("canceled") with longjmp &c.
* @katie-martin-fastly hasn't had time to work on https://github.com/rust-lang/rust/pull/76570 recently but hopes to get some more time soon =)

**Comment by nikomatsakis** [comment]
2020-11-17:

* Previous comment still basically accurate.

**Comment by nikomatsakis** [comment]
Update: PR is ready for review, and we'll have a longjmp blog post going out soon

**Comment by BatmanAoD** [comment]
2021-04-06:

* `"C-unwind"` PR was merged!
  * This accidentally introduced a change to `"C"` unwind behavior even without the feature flag; we will need to fix this before the next stable release. We have [alerted the release team](https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/.60.22C.22.60.20unwind.20issue.20for.20release.201.2E52/near/231848968) and are working on a fix.
  * There are a few more follow-up issues to address, listed [here](https://rust-lang.zulipchat.com/#narrow/stream/210922-project-ffi-unwind/topic/.60.22C-unwind.22.60.20next.20steps/near/231162649).
* a `longjmp` blog post was published, but we are prioritizing the `"C-unwind"` issues for now

**Comment by nikomatsakis** [comment]
Lang team planning meeting update:

* We should promote this project to "evaluation"
* On the topic of longjmp: 
    * Josh: Fairly unusual to see people using longjmp these days, should not sacrifice optimizablity
    * Josh: But it should be possible -- with enough care -- to longjmp without UB
    * Amanieu: this also affects functions that call `pthread_exit`
* Would be nice to open a PR and update the charter to include new scope (can link to the blog post)

**Comment by BatmanAoD** [comment]
* [updated charter](https://github.com/rust-lang/project-ffi-unwind/blob/master/charter.md)
* Follow-up issues for `"C-unwind"` remain our top priority.
   * In particular, we need to implement the specified "abort-on-unwind" behavior for `"C-unwind"` FFI calls in `panic=abort` mode.
* Regarding `longjmp`, we believe there's an LLVM bug causing incorrect code-gen when strict-aliasing is enabled in a frame that gets discarded by `longjmp`. We haven't yet discussed how to move forward, though we plan to open a bug report for it.

**Comment by nikomatsakis** [comment]
Update:

* @alexcrichton has a PR fixing various bugs and implementing the intended semantics, under review
* Plan of record is to 
    * remove the UB from panics in "C" while adding "C-unwind" as a target
    * once "C-unwind" is stabilized -- hopefully soon! -- add back in the UB for panics in "C"

**Comment by nikomatsakis** [comment]
Closing in favor of https://github.com/rust-lang/project-ffi-unwind/issues/36
