### ISSUE TITLE
Contracts proposal team review

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/lang-team#190]
# Summary

pnkfelix wants the team to discuss internally what questions we want answered by any future iteration of the Rust contracts proposal

# Background reading

pnkfelix is working on a doc here: https://hackmd.io/KqQGn5X_QAKwWxTk23E68Q

the original draft RFC is here: https://hackmd.io/w8AS2N09R76aXDFK9ogHBQ?view

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by rod-chapman** [comment]
I will be keen to attend.

**Comment by pnkfelix** [comment]
just to clarify: The goal of this meeting is for the Rust lang design team to identify what *questions* they want answered about contracts, *not* to get answers to those questions. We are not expecting a deep dive into the technology here.

Having said that, we welcome outside participants to join the meeting and observe our conversation.

**Comment by nikomatsakis** [comment]
Scheduled for Jan 18

**Comment by rod-chapman** [comment]
Can someone remind me of the time (and timezone) and the URL for this meeting please?

**Comment by sttaft** [comment]
Hi Rod.  Here is what I have for a meeting today at 1PM Eastern Standard Time:
<u></u><u></u>──────────<br>Topic: <a href="https://www.google.com/url?q=https://github.com/rust-lang/lang-team/issues/190&amp;sa=D&amp;source=calendar&amp;usd=2&amp;usg=AOvVaw2dXcgN5ekVFVlGZU7IZG-x" target="_blank">https://github.com/rust-lang/lang-team/issues/190</a><br> <br>Note: This meeting is primarily meant for team review; people outside the lang team / advisors are welcome to join and observe, but the meeting isn&#39;t meant for broad discussion.<br><br><u></u><br><u></u><a href="https://www.google.com/url?q=https://meet.jit.si/ferris-rules&amp;sa=D&amp;source=calendar&amp;usd=2&amp;usg=AOvVaw08-BXgHYFN5AcurlUXhhnV" target="_blank">https://meet.jit.si/ferris-rules</a><u></u>

**Comment by nikomatsakis** [comment]
Minutes here: https://github.com/rust-lang/lang-team/blob/master/design-meeting-minutes/2023-01-08-lang-team-questions-around-contracts.md
