### ISSUE TITLE
Design decisions around the `#[expect]` attribute

### ISSUE THREAD

**Issue by xFrednet** [rust-lang/lang-team#191]
# Summary

The `#[expect]` attribute as proposed in [RFC 2383](https://rust-lang.github.io/rfcs/2383-lint-reasons.html) adds a new attribute that suppresses lint emissions, but issues a warning if the expected lint doesn't trigger anymore. In the proposed RFC it was described as this:

> This RFC adds an `expect` lint attribute that functions identically to `allow`, but will cause a lint to be emitted when the code it decorates **does not** raise a lint warning. 

A working implementation of the attribute is available in nightly with the `lint_reasons` feature. See this [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=dd6dd677c432f4a3ceea4c0c22b7e09c) as an example. The goal of this meeting is to resolve the last questions remaining in the [tracking issue](https://github.com/rust-lang/rust/issues/54503).

## Questions

The questions also contain a collapsed explanation of the current behavior. (This might not work on the mobile view)

### 2. How should the `#[expect]` attribute interact with other lint attributes, like `allow`, `warn`, `deny`? [src](https://github.com/rust-lang/rust/issues/54503#issuecomment-1179588519)

For example, should this code fulfill the expectation or not?

```rs
#![feature(lint_reasons)]

#[expect(unused_variables)]
pub fn f() {
    #[warn(unused_variables)]
    let x = 1;
}
```

<details>
    <summary>Current implementation</summary>

Currently, expectations are only fulfilled by lint emissions directly affected by it. The example above would trigger two warnings, one for the unused value `x` and one for the fulfilled expectation.
</details>

### 3 Should an expectation be fulfilled, by a lint that would otherwise be allowed? [src](https://github.com/rust-lang/rust/issues/54503#issuecomment-1180773121)

For example, should this code fulfill the expectation or not?

```
#![feature(lint_reasons)]
#![allow(unused)]

#[allow(unsafe_code)]
pub fn f() {
    #[expect(unsafe_code)]
    unsafe {
    }
}
```

<details>
    <summary>Current implementation</summary>

The current implementation only checks if a lint is emitted at a node affected by the lint attribute. The example above would therefore fulfill the expectation, just like `#[warn]` would cause the code to trigger the lint. If this wouldn't be the case, the `#[expect]` attribute would change behavior based on the outer lint level. This can become confusing if the user defines a lint level via console arguments like this `cargo clippy -- -W clippy::pedantic`
</details>

# Background reading

* The tracking issue starting from the stabilization report: https://github.com/rust-lang/rust/issues/54503#issuecomment-1179563964
* The RFC: https://rust-lang.github.io/rfcs/2383-lint-reasons.html
* The draft documentation for the current implementation: https://github.com/rust-lang/reference/pull/1237

# Note

I'd like to attend the meeting as well. It would be awesome if I could be notified when the meeting has been scheduled. I'll also keep an eye on the calender :)

**Comment by nikomatsakis** [comment]
Hi @xFrednet! Question from the planning meeting this month. Do you think you would have time to author a document for the meeting to guide discussion?

**Comment by xFrednet** [comment]
Hey @nikomatsakis, it depends on when the meeting is, but I'd be up for it :). Do you have a template or example for the document? I tried to write the issue in a way that already guides the discussion :)

**Comment by nikomatsakis** [comment]
@xFrednet would March 8th work for you? Our meetings typically held at 13:00 US Eastern time (19:00 CEST). Regarding a template, I can send you some examples-- the key thing would be summarizing enough of the background material to have a self-contained discussion.

i.e., what are some of the proposed answers to those questions, and what are their pros/cons?

bonus points for taking an opinionated position about what you think is best :)

**Comment by nikomatsakis** [comment]
@xFrednet we're going to take a stab at better doc guidelines, but here are a few docs from past meetings that were productive:

* https://github.com/rust-lang/lang-team/blob/master/design-meeting-minutes/2021-10-13-where-the-where.md
* https://github.com/rust-lang/lang-team/blob/master/design-meeting-minutes/2022-10-05-provenance.md

Key point is to identify clearly the topics to discuss (and, often, what *not* to discuss) and to give the background needed for that.

Note that the docs include minutes of the actual converations and questions that happened.

One particular danger is that sometimes docs get too in the weeds with details, where really what is needed from the lang team is more alignment around the high-level goals, or which design features should be prioritized (i.e., the question is not "do we do X or Y" it's "which use case is more important").

**Comment by xFrednet** [comment]
@nikomatsakis The 8th of March works for me! Thank you for the examples, I'll read through them and take a stab at it :)

**Comment by xFrednet** [comment]
Hey @nikomatsakis, I've created a document that
