### ISSUE TITLE
Design Meeting: Field Projection

### ISSUE THREAD

**Issue by y86-dev** [rust-lang/lang-team#194]
# Summary

The topic of this design meeting is the field projection [RFC](https://github.com/rust-lang/rfcs/pull/3318). The goals are:
- finding a suitable API to express field projection,
- discern the extent of such projections (i.e. are projections on iterators allowed?),

# Background reading

- the RFC: https://github.com/rust-lang/rfcs/pull/3318
- pre-RFC discussion: https://internals.rust-lang.org/t/pre-rfc-field-projection/17383/57

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by y86-dev** [comment]
As I am pretty short on time this month, I would prefer it if the meeting takes place in march or later.

**Comment by joshtriplett** [comment]
@y86-dev Would you propose that the design meeting use the RFC itself as a design document, or do you intend to propose a design document that has more focused design questions or similar?

At a minimum, it would be helpful to have a set of questions you'd like the lang team to focus on when looking at this.

**Comment by tmandry** [comment]
Here are some guidelines on design documents from https://github.com/rust-lang/lang-team/issues/191#issuecomment-1423088440:

> We're going to take a stab at better doc guidelines, but here are a few docs from past meetings that were productive:
> 
> * https://github.com/rust-lang/lang-team/blob/master/design-meeting-minutes/2021-10-13-where-the-where.md
> * https://github.com/rust-lang/lang-team/blob/master/design-meeting-minutes/2022-10-05-provenance.md
> 
> Key point is to identify clearly the topics to discuss (and, often, what _not_ to discuss) and to give the background needed for that.
> 
> Note that the docs include minutes of the actual converations and questions that happened -- best thing is to author the doc in hackmd so we can live edit it during the meeting.
> 
> One particular danger is that sometimes docs get too in the weeds with details, where really what is needed from the lang team is more alignment around the high-level goals, or which design features should be prioritized (i.e., the question is not "do we do X or Y" it's "which use case is more important").

**Comment by y86-dev** [comment]
I intent to write a design document that outlines the core problem and the desired properties of a solution (these would also be a discussion point). Thanks for the links, I will take them into account when writing.

**Comment by nikomatsakis** [comment]
Scheduled for Mar 29

**Comment by tmandry** [comment]
This meeting happened. Doc link: https://hackmd.io/@y86-dev/SkkfRkzWh
