### ISSUE TITLE
Interface between opsem and lang team

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#196]
# Summary

Reprise the roles of lang vs opsem team and work through the "interface" between the two. 

Doc will work through examples scenarios like:

* Lang team wanting to stabilize a feature that interacts with unsafe code
* Lang team wanting to add constraints or high-level direction, or authorize optimizations
* Opsem team raising concerns 

# Background reading

None.

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by nikomatsakis** [comment]
cc @ralfjung and @jakobdegen

**Comment by pnkfelix** [comment]
currently scheduled for 2023-03-01

**Comment by RalfJung** [comment]
Each time I get invited to one of these I spend minutes going through the website to figure out the time of the meeting.^^ Looks like it's 7pm my time. That should work.

**Comment by tmandry** [comment]
This meeting happened; can someone drop a link to the hackmd?
