### ISSUE TITLE
Temporary lifetimes

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#197]
# Summary

Some of the rules for temporary lifetimes in Rust are a common source of confusion and bugs.

We will author a document highlighting some of the known problems, proposing some of the alternatives, and exploring the pros/cons. 

Any changes here will affect the semantics of existing programs and thus should be tied to the edition, making this a time-sensitive investigation.

# Background reading

None.

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by nikomatsakis** [comment]
Scheduled for March 15.

**Comment by tmandry** [comment]
This meeting happened; can someone drop a link to the hackmd?
