### ISSUE TITLE
inline-asm

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#20]
# Summary

Pursuing a stable notation for inline assembly.

# Links

* Lead: @Amanieu
* Lang-team liaison: @joshtriplett 
* [Repository](https://github.com/rust-lang/project-inline-asm/)
* Zulip stream [`#project-inline-asm`](https://rust-lang.zulipchat.com/#narrow/stream/216763-project-inline-asm)

**Comment by nikomatsakis** [comment]
2020-06-15: 

Some updates:

* Inside Rust blog post was posted which got a lot of feedback, some of which is captured into the tracking issue. 
* Common problem is that people aren't sure how to format, and we took a first pass at writing up a style RFC. Team is kind of dormant right now but would be good to rev up and take a look at this.
* This revealed that multi-line inline assembly is hard to format, so we discussed the idea of multiple strings, one per logical line of assembly, which gives rustfmt a lot more freedom. Implemented in PR rust-lang/rust#73364.

**Comment by joshtriplett** [comment]
[Style RFC](https://github.com/rust-dev-tools/fmt-rfcs/issues/152) (Needs updating for the new multi-line style)

**Comment by nikomatsakis** [comment]
2020-06-22:

* Change to allow multiple logical lines of inline assembly has been merged.
* Blog post example has been updated so that people have that available.
* This means people can write code that rustfmt can properly indent, should offer substantial formatting improvements.
* Still awaiting checkmarks on the RFC. No blocking issues that folks in meeting are aware of.

**Comment by nikomatsakis** [comment]
2020-07-06:

* RFC https://github.com/rust-lang/rfcs/pull/2850 is in FCP and has 3 more days to go.

**Comment by Lokathor** [comment]
i think you meant https://github.com/rust-lang/rfcs/pull/2873

**Comment by nikomatsakis** [comment]
2020-07-20:

* Status: Implemented, just needs some time to bake. Probably at this point we want to 'hold off' for some period of time. Shooting to stabilize "early next year", most likely. Won't paste comments until there are major updates.

**Comment by nikomatsakis** [comment]
2020-09-21:

* There's been some implementation work towards adding MIPS support, which would be a good sign that it's possible to evolve this forward towards adding more architectures.

**Comment by Amanieu** [comment]
In fact we've already had PRs adding support for [NVPTX](https://github.com/rust-lang/rust/pull/72439) and [Hexagon](https://github.com/rust-lang/rust/pull/73214).

**Comment by nikomatsakis** [comment]
2020-10-19:

* Some renewed discussion on whether inline assembly should be exposed as `asm!` or `core::arch::TARGET::asm!`. 
* Most of the time your assembly is target specific. But there are also cases where it's used in a surprisingly portable way (32, 64 bit, for example, or custom directives). 
* This will require a decision before stabilization, recommend creating an issue with a proposal and the pros/cons and other considerations at that point.
* Some issues around LLVM version checking but new release may help.

**Comment by joshtriplett** [comment]
2021-02-03: update on stabilization blockers at https://github.com/rust-lang/rust/issues/72016#issuecomment-761616910

**Comment by nikomatsakis** [comment]
Stabilized!
