### ISSUE TITLE
Keyword Generics Initiative Update

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/lang-team#203]
# Summary

It's been a while since the Keyword Generics Initiative group has met with the lang team. We'd like to meet again so we can update the lang team with our progress, and discuss future directions.

# Background reading

- [Announcing the Keyword Generics Initiative](https://blog.rust-lang.org/inside-rust/2022/07/27/keyword-generics.html)
- [Keyword Generics Progress Report: February 2023](https://blog.rust-lang.org/inside-rust/2023/02/23/keyword-generics-progress-report-feb-2023.html)
- [Koka: Programming with Row Polymorphic Effect Types](https://arxiv.org/abs/1406.2061)

**Other stuff that may come up during conversation:**

- [Thoughts on Async Closures](http://smallcultfollowing.com/babysteps/blog/2023/03/29/thoughts-on-async-closures)
- [Trait transformers (send bounds, part 3)](https://smallcultfollowing.com/babysteps/blog/2023/03/03/trait-transformers-send-bounds-part-3/)

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

---

cc/ @rust-lang/initiative-keyword-generics

**Comment by yoshuawuyts** [comment]
Updating my availability for this month's planning session: I won't be available for one week (week 20) from 2023-05-12 (Friday) until 2023-05-20 (Saturday).

**Comment by nikomatsakis** [comment]
Scheduled for 2023-06-07 and created a [placeholder document for that](https://hackmd.io/JZUXMeatSmiZsf-NgZIsrA)

**Comment by yoshuawuyts** [comment]
We had the meeting; closing this!
