### ISSUE TITLE
Return type notation and the Send bound problem

### ISSUE THREAD

**Issue by tmandry** [rust-lang/lang-team#208]
# Summary

*Please describe your meeting topic here. It doesn't have to be very long, but
it's always good to try and identify a concrete question to be answered or
narrow topic for discussion. Nobody likes a rambly meeting.*

Discuss proposals for dealing with `Send` bounds on async fn and `-> impl Trait` in traits.

# Background reading

*Include any links to material that folks ought to try to read before-hand.*

https://blog.rust-lang.org/inside-rust/2023/05/03/stabilizing-async-fn-in-trait.html

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by nikomatsakis** [comment]
Minutes https://github.com/rust-lang/lang-team/blob/master/design-meeting-minutes/2023-05-24-return-type-notation.md
