### ISSUE TITLE
Rust 2024 survey

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#209]
# Summary

The Rust 2024 edition is coming soon! Any land changes should be RFC'd this year. Let's do a survey of things that could be done over the edition so that we can start tracking as we go into the summer.

# Background reading

*Include any links to material that folks ought to try to read before-hand.*

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by joshtriplett** [comment]
Some potentially useful links:

- https://blog.rust-lang.org/inside-rust/2022/04/04/lang-roadmap-2024.html
- https://github.com/rust-lang/rust/labels/A-edition-2024
- https://github.com/rust-lang/rust/labels/lang-team-202x-edition

**Comment by nikomatsakis** [comment]
Scheduled for 2023-06-28 and [placeholder doc created](https://hackmd.io/itGzgM1fQl-oh4d1iP8sFg)

**Comment by Jules-Bertholet** [comment]
https://github.com/rust-lang/rust/issues/59878 would be nice to fix, if negative impls can be stabilized on time

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rfcs/pull/3325 is intended to be edition sensitive.

Not sure if there is any point in giving another shot at "removing long-deprecated items that are unsound or almost impossible to use soundly" (`mem::uninitialized`, `before_exec`).

**Comment by Jules-Bertholet** [comment]
Some more open RFCs that are potentially edition-sensitive:

- https://github.com/rust-lang/rfcs/pull/2484 (deprecate `as`?)
- https://github.com/rust-lang/rfcs/pull/2937 (deprecate `static mut`?)
- https://github.com/rust-lang/rfcs/pull/3240
- https://github.com/rust-lang/rfcs/pull/3319 (future possibility: `?Sized` → `?Aligned`)
- https://github.com/rust-lang/rfcs/pull/3373
- https://github.com/rust-lang/rfcs/pull/3396
- https://github.com/rust-lang/rfcs/pull/3410 (future possibility)

Open issues:

- All of https://github.com/rust-lang/rust/labels/lang-team-202x-edition
- Much of https://github.com/rust-lang/rust/labels/A-edition-2018-lints
- Much of https://github.com/rust-lang/rust/labels/C-future-compatibility
- https://github.com/rust-lang/rust/issues/35121 (inference fallback)
- https://github.com/rust-lang/rust/issues/43781 (`doc_auto_cfg`)
- https://github.com/rust-lang/rust/issues/49441
- https://github.com/rust-lang/rust/issues/67264
- https://github.com/rust-lang/rust/issues/71668
- https://github.com/rust-lang/rust/issues/80619
- https://github.com/rust-lang/rust/issues/89151 (RFC future possibility)
- https://github.com/rust-lang/rust/issues/94978
- https://github.com/rust-lang/rust/issues/95228 (deprecate pointer-integer `as` casts?)
- https://github.com/rust-lang/rust/issues/98862
- https://github.com/rust-lang/rust/issues/99195 and https://github.com/rust-lang/rust/issues/108069  (making `overflowing_literals` deny or a hard error)
- https://github.com/rust-lang/rust/issues/100706

**Comment by tgross35** [comment]
I know there was some discussion about changing the `Range`/`Iter`/`IntoIterator`/`Copy` fiasco at some point, but I don't believe a concrete proposal came out of it, or if it is even "fixable"

**Comment by bstrie** [comment]
@tgross35 I think the Range situation is improvable, although naturally having an RFC is a prerequisite and nobody's going to hold up the edition if an RFC doesn't materialize. I have some thoughts in that area that might lead to an RFC.

**Comment by tgross35** [comment]
I did find some discussion about this https://github.com/rust-lang/rfcs/issues/2848. It seems like the kind of thing where somebody just needs to start writing an RFC and see how well it sticks.

@bstrie if you want to throw some loose ideas into a HackMD document, I don't mind helping formulate them into an RFC (I'm sure others would join too)

**Comment by Jules-Bertholet** [comment]
https://github.com/rust-lang/rust/labels/WG-epoch also merits review

**Comment by fmease** [comment]
I know this issue is not the right place (the meeting has already happened as far as I can tell) but since there isn't a proper Zulip stream yet, I'm just gonna nominate the (breaking) feature [`lazy_type_alias`](https://github.com/rust-lang/rust/issues/112792) here for inclusion into Rust 2024. It still needs some polish though.

This directly addresses the following point found at the bottom of the HackMD doc:

> ### other things that came up after the meeting
> * Remove where clauses on type aliases or make them work.

**Comment by yoshuawuyts** [comment]
@rust-lang/wg-async  has a roadmap item for extending the 2024 prelude here: https://github.com/rust-lang/wg-async/issues/310. We don't yet have consensus among ourselves about which items we want to add, but I hope we can arrive at that soon.

**Comment by tgross35** [comment]
@bstrie I don't know whether you had time to put anything together, but I started a rough outline https://hackmd.io/@8W5l8q6-Qyyn_vKh2-L0RQ/SJ0sBpb22. It should be open for editing if anyone wants to contribute (discussion should probably happen in comments in the doc so as to not derail this thread).
