### ISSUE TITLE
RFC review: Add f16 and f128 float types -- RFC#3453

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/lang-team#218]
https://github.com/rust-lang/rfcs/pull/3453

**Comment by pnkfelix** [comment]
scheduled for 2023-09-20

**Comment by scottmcm** [comment]
I might not make the meeting for this, but my thoughts are currently like https://github.com/rust-lang/rfcs/pull/3453#issuecomment-1698198331 -- that I think from a lang perspective this seems fine, but that actually getting "full" support for things might not happen for a *very* long time.

So my note for a discussion might be whether we'd be ok with this even if, for a while, say only literals and conversions and ABI support existed for them, perhaps not even things like `*`.

**Comment by aaronfranke** [comment]
@scottmcm I think full support is both ideal and important, but this should not block just getting the type in, if that can be done faster. Having only literals and conversions is better than nothing for now. Basic math operations like addition and multiplication are very important too, only second to literals and conversions, so we must have them eventually.
