### ISSUE TITLE
Meeting proposal: Unsafe extern blocks

### ISSUE THREAD

**Issue by tmandry** [rust-lang/lang-team#223]
# Summary

Simply declaring extern items, even without ever using them, can cause Undefined Behavior. When performing cross-language compilation, attributes on one function declaration can flow to the foreign declaration elsewhere within LLVM and cause a miscompilation. In Rust we consider all sources of Undefined Behavior to be unsafe, and so we must make declaring extern blocks be unsafe. The up-side to this change is that in the new style it will be possible to declare an extern fn that's safe to call after the initial unsafe declaration.

In Edition 2024 it is unsafe to declare an extern function or static, but external functions and statics can be safe to use after the initial declaration.

# Background reading

https://github.com/rust-lang/rfcs/pull/3484

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by tmandry** [comment]
cc @Lokathor

**Comment by Lokathor** [comment]
Thanks but I never have Wednesday free, so just hold it without me.

**Comment by RalfJung** [comment]
> Simply declaring extern items, even without ever using them, can cause Undefined Behavior. 

FWIW this is not a fact of nature, it's an LLVM thing inherited from C. We could also try to work towards fixing that.
