### ISSUE TITLE
weak alias types for Rust 2024

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#227]
# Summary

In the @rust-lang/types meetup ([notes here](https://hackmd.io/hnJkp_ZdT6aVUu-7piUdsQ)), we were discussing the possibility of migrating "Weak Alias Types" (i.e., `type Foo = Bar` as a top-level item) to properly respect where-clauses:

```rust
type Foo<T> = Vec<T>
where
    T: Ord; // <-- this would be enforced!
```

We realized that there is a lang-team design question to be resolved, which is whether we want to have some kind of implied bounds so that users don't have to write everything. In the meeting, everybody wanted implied outlives bounds (same as with structs) like this...

```rust
type Foo<'a, T> = &'a T; // implied `T: 'a`
```

...but it was less clear whether to have other kinds of implied bounds...

```rust
struct NeedsClone<T: Clone> { t: T }
type Foo<T> = NeedsClone<T>; // Is this accepted?
```

There were two basic arguments, one by analogy to struct (which argues this should be an error) and one by conservatism (it's annoying, and if we move forward with implied bounds in other places, we may want it here, so it's odd to first lint everyone to add where-clauses, and then make them redundant).

This seems ultimately like a @rust-lang/lang decision, so we are opening this design meeting proposal.

# Background reading

*Include any links to material that folks ought to try to read before-hand.*

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by nikomatsakis** [comment]
I am volunteering to author up a doc with background and motivation for the design meeting.

**Comment by fmease** [comment]
I did happen. Minutes: https://hackmd.io/LCUSAX5LSfqc4m7N4CWNPw
