### ISSUE TITLE
Discuss RFC 2442: Simple postfix macros

### ISSUE THREAD

**Issue by traviscross** [rust-lang/lang-team#247]
# Summary

We plan to discuss [RFC 2442](https://github.com/rust-lang/rfcs/pull/2442), "Simple postfix macros".

If we have time, we'll also discuss [RFC 3295](https://github.com/rust-lang/rfcs/pull/3295), "Postfix match".

@joshtriplett is preparing a document for us.

# Background reading

- [RFC 2442](https://github.com/rust-lang/rfcs/pull/2442)
- [RFC 3295](https://github.com/rust-lang/rfcs/pull/3295)

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by joshtriplett** [comment]
Document: https://hackmd.io/zsu_30qRRyezzDr6xIQpkA?both

**Comment by joshtriplett** [comment]
Capturing the summary here:

- Everyone on the team agreed that non-type-based dispatch of postfix macros was fine.
- The desugaring in the RFC doesn't work for places (e.g. $self = $x). We need to either define a mechanism/desugaring that works for that, or decide we don't need to support that. Places work with closures today (e.g. |y| { x = y }), but we need to decide if we want it to work with postfix maros. We also need to figure out if it's simpler to support this or to not support this.
- Niko and Tyler expressed that they're not sure we have to mandate eager evaluation, and people may not necessarily misuse it. Niko noted that this would be simpler to implement if we didn't mandate that. Tyler expressed willingness to go ahead with an eager-required implementation, though.
- We could potentially make eager-evaluated macro arguments a separate, orthogonal feature. For instance, $foo:expr-eval. (We would still have the option of mandating the use of that with self.)

**Comment by joshtriplett** [comment]
@Nadrieril suggested `place` for the desugaring, instead of `autoref`.
