### ISSUE TITLE
Extended triage meeting 2024-03-20

### ISSUE THREAD

**Issue by traviscross** [rust-lang/lang-team#257]
# Summary

We decided to do an extended triage meeting on 2024-03-20 in our design meeting slot to help catch up on the backlog.

We were also interested in leaving space here for discussing the situation on the new range types if we could have new input ready for us at that point.  @pitaj is working on pulling that together for us.

We'll also plan to discuss the situation on rust-lang/rust#121610, and @oli-obk and @RalfJung are planning to join us for that (we'll plan to discuss that first).

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by RalfJung** [comment]
> We'll also plan to discuss the situation on https://github.com/rust-lang/rust/issues/121610, and @oli-obk and @RalfJung are planning to join us for that (we'll plan to discuss that first).

I started working on a [background document](https://hackmd.io/3fj1WHGIT7-l8hRHxcKS8A) for that part. I don't think I will have time to extend this further, but if someone else wants to add some details on how interior mutability factors in, please feel free. :)

**Comment by pitaj** [comment]
> We were also interested in leaving space here for discussing the situation on the new range types if we could have new input ready for us at that point. @pitaj is working on pulling that together for us.

I [wrote up a document](https://hackmd.io/@uhs6rVdLTSS0gnie4q0fqA/ryjYJW2pa) for this. Hopefully I've given you enough time to read it over.

If you have any questions, let me know. I don't know what time your meetings are or if you ever bring in outsiders, but I should be available for some synchronous conversation tomorrow during NA daylight hours, should you want to discuss.

[Raw data I extracted from crater](https://github.com/rust-lang/lang-team/files/14659048/data.zip)
