### ISSUE TITLE
Design meeting: New Range types for Rust 2024

### ISSUE THREAD

**Issue by traviscross** [rust-lang/lang-team#259]
# Summary

After we last discussed this on 2024-02-07, we made a number of [requests](https://github.com/rust-lang/rfcs/pull/3550#issuecomment-1935112286) for further analysis and data collection.  @pitaj has now [reported](https://github.com/rust-lang/lang-team/issues/257#issuecomment-2008487144) having done that.

The design document with this data and analysis is here:

https://hackmd.io/@uhs6rVdLTSS0gnie4q0fqA/ryjYJW2pa

And the raw data he extracted from crater is here:

https://github.com/rust-lang/lang-team/files/14659048/data.zip

We may want to use a design meeting to discuss this.

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by nikomatsakis** [comment]
This is not happening for Rust 2024 and the RFC has been accepted etc.

**Comment by joshtriplett** [comment]
Also, we did review this data asynchronously.
