### ISSUE TITLE
Design meeting: async closures

### ISSUE THREAD

**Issue by traviscross** [rust-lang/lang-team#262]
# Summary

Let's talk about the ongoing work on async closures.

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by nikomatsakis** [comment]
Closing, this was done.
