### ISSUE TITLE
Design meeting: Planning/RTN 2024-06-12

### ISSUE THREAD

**Issue by traviscross** [rust-lang/lang-team#270]
# Summary

Let's meet for planning and to review the RTN RFC.

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by nikomatsakis** [comment]
Not sure what scope we have in mind but my availability...

* June 19 -- yes
* June 26 -- yes
* July 3 -- yes

...also, I'd like to ensure we schedule <https://github.com/rust-lang/lang-team/issues/271>.
