### ISSUE TITLE
Design meeting: Profiles

### ISSUE THREAD

**Issue by traviscross** [rust-lang/lang-team#289]
# Summary

We'll be meeting to talk about the proposal for profiles for Rust.

# Background reading

*Include any links to material that folks ought to try to read before-hand.*

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by Lokathor** [comment]
hey @traviscross are there links to the meeting notes or... well *any* other context that could be put on this issue for people who find it later?

**Comment by traviscross** [comment]
The link to the minutes is over in the side bar under "Projects > T-lang design meeting schedule".

**Comment by Lokathor** [comment]
On mobile at least there's no sidebar, and if i go to the project board you mentioned and then search "profile" then there's two entries (including this one) that both refer to a meeting that happened, but without any minutes being linked.

**Comment by RalfJung** [comment]
It's visible on desktop:
https://hackmd.io/COdIdx2rTEWZtNAjIqvUyA
