### ISSUE TITLE
Design meeting: Trait modifiers / RFC 3710

### ISSUE THREAD

**Issue by traviscross** [rust-lang/lang-team#294]
# Summary

We'll be discussing:

- https://github.com/rust-lang/rfcs/pull/3710

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by nikomatsakis** [comment]
Document link:

https://hackmd.io/@rust-lang-team/ryxu3YLx1e
