### ISSUE TITLE
Add placement by return (GCE, unsized returns)

### ISSUE THREAD

**Issue by PoignardAzur** [rust-lang/lang-team#31]
# Proposal

This is a summary of the proposal that was initially proposed as [PR-2884 in the RFC repository](https://github.com/rust-lang/rfcs/pull/2884).

## Summary

Implement Guaranteed Copy Elision (GCE) in simple cases, so that functions returning any non-trivial amount of data are guaranteed to write that data directly to the slice of memory that will store it at the end of the return chain.

In cases where GCE is possible, allow functions to return unsized types directly (rather than boxed versions or references to these types). To make this possible, functions returning unsized types are split into two functions, as a special kind of generator:

* The first half yields the memory layout of the return value
* The second half writes the return value into a given chunk of memory (which must have the previously yielded layout).

Various unsafe functions can then call the first half, allocate memory based on the given layout, and pass the allocated memory to the second half. Simplified example:

```rust
impl<T: ?Sized> Box<T> {
    fn new_with<F: FnOnce() -> T>(f: F) -> Self {
        unsafe {
            let state = CALL_FIRST_HALF_UNSIZED(f);
            let p = NonNull::from_mut_ptr(GlobalAlloc.alloc(state.layout()));
            CALL_SECOND_HALF_UNSIZED(f, state, p.as_mut_ptr() as *mut MaybeUninit<T>);
            Box { p }
        }
    }
}
```

## Motivation

Although this might seem like a niche feature at first glance, it has a surprising number of use cases, and enables some highly-demanded developments. Some use cases:

- Guaranteed [placement](https://old.reddit.com/r/rust/comments/hemjx0/boxnew_lies_data_is_created_on_the_stack_then/) for performance-critical code that needs to create large objects.
- Creating trait objects in no_std environments.
  - Writing [no_std dylibs with existential types](https://internals.rust-lang.org/t/a-plugin-system-for-business-applications/12313/7).
- [Unsized constants](https://internals.rust-lang.org/t/unsized-constants).
- [async traits](https://www.smallcultfollowing.com/babysteps/blog/2019/10/26/async-fn-in-traits-are-hard/#complication-3b-no-right-choice-for-x-in-dyn-databasegetusers--x).
- Allocator-agnostic array concatenation.

I have empirically observed that the RFC has been quoted fairly often in discussions both on r/rust and the rust-internals forums, in answer to people asking "I need to find a way to do X, how could rust implement it?"

## Links and related work

- [Original topic](https://internals.rust-lang.org/t/pre-rfc-minimal-flexible-placement-and-returning-unsized-types/10032), though several people independently came up with the idea.
- [RFC PR 2884](https://github.com/rust-lang/rfcs/pull/2884).
- [GCE in C++](https://jonasdevlieghere.com/guaranteed-copy-elision/).

# Mentors or Reviewers

_No mentor yet._

# The Major Change Process

Once this MCP is filed, a Zulip topic will be opened for discussion. Ultimately, one of the following things can happen:

* If this is a small change, and the team is in favor, it may be approved to be implemented directly, without the need for an RFC.
* If this is a larger change, then someone from the team may opt to work with you and form a project group to work on an RFC (and ultimately see the work through to implementation).
* Alternatively, it may be that the issue gets closed without being accepted. This could happen because:
    * There is no bandwidth available to take on this project right now.
    * The project is not a good fit for the current priorities.
    * The motivation doesn't seem strong enough to justify the change.

**Comment by jethrogb** [comment]
> Original topic, though several people independently came up with the idea.

“Original topic” links to the incorrect URL?

**Comment by PoignardAzur** [comment]
Fixed.

**Comment by nikomatsakis** [comment]
Hey @rust-lang/lang -- we haven't seen anyone volunteering to serve as liaison for this project. If we're not able to find a liaison in the next week or so, I'm going to close the issue. If you think you might like to serve as a liaison, even if you don't have bandwidth right now, please do speak up -- we can always put the proposal on the "deferred list" to pick up when we have time.

**Comment by nikomatsakis** [comment]
Discussed in the @rust-lang/lang meeting.

* This will require close cooperation between lang and compiler.
* We don't think the bandwidth or expertise is available right now.
* However, we also think that we don't have to block the *implementation* work on making it required. i.e., if compiler team has review bandwidth available, then we could implement the optimizations, and later decide whether to they ought to be required.

**Comment by nikomatsakis** [comment]
I'm going to mark this as "disposition close", since we are not likely to accept as lang-team project, but we'll review this in next triage meeting a final time to see if there are add'l comments that affect the outcome.

**Comment by nikomatsakis** [comment]
OK, we're going to close this but encourage the author to pursue the implementation side of things with the compiler team (this seems like a optimization working group consideration). Thanks @PoignardAzur! We would be happy to revisit the idea of making this guaranteed once the optimization is implemented.

**Comment by PoignardAzur** [comment]
I'm probably going to quit my job around January, and then I'll be spending a few months hacking on Rust projects full-time. I'm interested in working on the implementation of GCE/NRVO then.

Do you know if we could arrange some sort of mentoring around that period? Alternatively, what resources should I look at to get a decent understanding of how MIR represents values and operations?

(I'm going to start looking at rustc "E-Easy" issues in the meantime)
