### ISSUE TITLE
Stream trait and related issues

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#34]
# Summary

In the context of the Async Foundations group, @nellshamrell has been drafting an RFC to stabilize the `Stream` trait. See e.g. https://github.com/rust-lang/wg-async-foundations/pull/15 for the latest round of edits. While the actual content of the RFC is perhaps more libs than lang (introducing a trait), the choice of whether or not to introduce this trait touches on a number of lang issues, particularly around forwards compatibility, and I thought it would be good to discuss as a group.

Some of the issues I thought particularly relevant:

* Method dispatch ambiguity issues around migrating extension methods from futures crate to the stdlib (a common scenario that also applies to e.g. itertools for iterators)
* Coherence issues if we attempted to bridge a `Stream` trait with a future `LendingStream` (a.k.a., "streaming stream" or "attached stream") trait
* The possibility of generator syntax and potential compatibility issues that may arise there

cc @rust-lang/wg-async-foundations @sfackler 

# Background reading

Draft RFC: https://github.com/rust-lang/wg-async-foundations/pull/15

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by nikomatsakis** [comment]
We were thinking of scheduling this for Aug 12 -- cc @withoutboats @nellshamrell @cramertj and @yoshuawuyts are y'all available on that date for the lang team design slot? (And others, those are folks who expressed interest to me in the past...)

**Comment by yoshuawuyts** [comment]
@nikomatsakis yes, that works for me!

**Comment by nellshamrell** [comment]
Works for me!

**Comment by nikomatsakis** [comment]
Scheduled: [calendar event](https://calendar.google.com/event?action=TEMPLATE&tmeid=Y2JuMml0cmNlanVhMWJmNWVpNjA0dGlmOG1fMjAyMDA4MTJUMTcwMDAwWiByZWN1ZDRiOW84Y21jMG01cm1yMDMzcDVua0Bn&tmsrc=recud4b9o8cmc0m5rmr033p5nk%40group.calendar.google.com&scp=ALL)

**Comment by cramertj** [comment]
Yes, I'll be there!

**Comment by nikomatsakis** [comment]
Hmm, so I think we ought to postpone this by a week. In light of the [Mozilla layoffs](https://blog.mozilla.org/blog/2020/08/11/changing-world-changing-mozilla/) there is an important meeting that I have to attend that conflicts with this slot.

**Comment by nikomatsakis** [comment]
I took the liberty of moving calendar invite to Aug 19.

**Comment by LucioFranco** [comment]
That cal event shows may 13th? Just to confirm this is aug 18 at 1p eastern time?

**Comment by tmandry** [comment]
Looks like this was [bumped again](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/design.20meeting.20for.20stream.20rust-lang.2Flang-team.2334) to next week.

**Comment by nikomatsakis** [comment]
Minutes posted: https://github.com/rust-lang/lang-team/blob/master/design-meeting-minutes/2020-11-04-RFC-2580-and-custom-dst.md

**Comment by programmerjake** [comment]
@nikomatsakis looks like you accidentally posted the wrong url
