### ISSUE TITLE
MCP: repr(align(ptr))

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/lang-team#35]
The `AtomicPtr` type needs [three lines of cfg_attr](https://doc.rust-lang.org/src/core/sync/atomic.rs.html#183-185) just to try and say what it really wants to say, "I am aligned to the size of a pointer". This is slightly silly, and what's worse it's actually a little error prone because if the pointer width were ever smaller (unlikely) or larger (not impossible) then suddenly none of the cfg_attr would apply and not only would it not have the right alignment it wouldn't even have repr(C), which could make _other code_ that assumes `AtomicPtr` has repr(C) also suddenly be UB.

Conclusion the `align()` attribute should allow a value of `ptr` to request pointer alignment for your type in a "blessed" portable way.

**Comment by nikomatsakis** [comment]
Since @scottmcm has assigned themselves as liaison, the next step here is to author a charter.

**Comment by Lokathor** [comment]
Can do, though I'll wait for the PR that has the charter template in it to actually merge first.
