### ISSUE TITLE
Stabilizing a subset of const generics

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/lang-team#37]
# Summary

I want to propose that we get a subset const generics on track to stabilization in the near future. We should have a meeting to discuss the specifics and attempt to achieve consensus on this plan.

# Background reading

* https://without.boats/blog/shipping-const-generics/
* https://internals.rust-lang.org/t/stabilizing-a-const-generics-mvp/12727/
* https://github.com/rust-lang/compiler-team/issues/332

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by nikomatsakis** [comment]
As discussed on Zulip, we are thinking of doing this meeting this week, July 22 -- @withoutboats can you confirm availability for that slot?

**Comment by withoutboats** [comment]
Yes I plan to attend.

**Comment by nikomatsakis** [comment]
Scheduled for July 22 design meeting.

**Comment by nikomatsakis** [comment]
Minutes and recording are available: https://github.com/rust-lang/lang-team/blob/master/design-meeting-minutes/2020-07-22-Const-generics-MVP.md
