### ISSUE TITLE
MCP: Elevated privileges for #[test_util]

### ISSUE THREAD

**Issue by Wodann** [rust-lang/lang-team#38]
# Proposal

## Motivation, use-cases, and solution sketches

When writing unit tests using the `#[test]` proc_macro, you get access to private functions and member variables. When projects get larger it often makes sense to introduce utility functions for your tests that are shared between unit tests of different modules.

A problem with those test utils is that they lose the elevated privileges that would e.g. allow you to call a constructor with private fields. To solve this you could make the respective fields `pub(crate)` but that would leak beyond just a test use case.

I propose the addition of a `#[test_util]` proc_macro that would elevate privileges of such utility functions in test environments only. I am open to ideas for naming.

File: `lib.rs`
```rust
mod foo;
mod bar;

#[cfg(test)]
mod test_utils;
```

File: `foo.rs`
```rust
pub struct Foo {
    pub(crate) a: String, // leak data to allow `create_fake_foo` to construct
    pub b: f32,
}

// Logic goes here

#[cfg(test)]
mod tests {
    #[test]
    test_foo() {
        let foo = create_fake_foo();
        // unit test goes here
    }
}
```

File: `bar.rs`
```rust
use crate::foo::Foo;

struct Bar(Foo);

// Logic goes here

#[cfg(test)]
mod tests {
    #[test]
    test_foo() {
        let foo = create_fake_foo();
        let bar = Bar(mock);
        // unit test goes here
    }
}
```

File: `test_utils.rs`
```rust
// #[test_util] would prevent the need to leak `Foo`'s fields in non-test environments
pub(crate) fn create_fake_foo() {
    Foo {
        a: "foo".to_string(),
        b: 1.234,
    }
}
```

## Links and related work

[Original Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Elevated.20priviliges.20for.20.23.5Btest_util.5D)

# The Major Change Process

Once this MCP is filed, a Zulip topic will be opened for discussion. Ultimately, one of the following things can happen:

* If this is a small change, and the team is in favor, it may be approved to be implemented directly, without the need for an RFC.
* If this is a larger change, then someone from the team may opt to work with you and form a project group to work on an RFC (and ultimately see the work through to implementation).
* Alternatively, it may be that the issue gets closed without being accepted. This could happen because:
    * There is no bandwidth available to take on this project right now.
    * The project is not a good fit for the current priorities.
    * The motivation doesn't seem strong enough to justify the change. 

You can read [more about the lang-team MCP process on forge].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/lang/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by nikomatsakis** [comment]
Discussed in today's triage meeting.

* Most members of the team were unaware of this quirk of our privacy rules, suggesting it's little used. We don't want to try and remove this feature, but we also aren't inclined to expand it at this time.

Thanks for the suggestion @Wodann. However, we are going mark as disposition close and enter final comment period. We will revisit next triage meeting!

**Comment by nikomatsakis** [comment]
OK, based on the above, we're going to close this proposal. Thanks @Wodann for the suggestion.
