### ISSUE TITLE
Extend the reference team to "lang docs" team

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/lang-team#47]
## (Original) Summary

(I'm not sure which the template I should use, so opening as a blank issue.)
Currently, we _don't have_ maintainers of the nomicon.
We're tracking its toolstate and of course, we should make it up-to-date as possible. I think it's reasonable to form the nomicon team and maintain regularly, like the reference.
I can take a lead, and feel free to comment here if you're interested in helping maintain. It'd be great if some of the lang team participates in.

related Zulip topic: https://rust-lang.zulipchat.com/#narrow/stream/196563-t-lang.2Fwg-meta/topic/maintain.20status.20of.20nomicon

**Comment by Lokathor** [comment]
I'd be interested in staying on top of the situation, I already deal in a lot of unsafe code as it is.

**Comment by joshtriplett** [comment]
We talked about this a little on Zulip. Proposal: let's add interested people to the team that currently maintains the reference, and expand that team's charter to also include the nomicon and other "lang docs".

**Comment by JohnTitor** [comment]
Could we nominate this for the next triage meeting?

**Comment by JohnTitor** [comment]
Any updates on this?

**Comment by JohnTitor** [comment]
I forgot to close this, thanks folks!
