### ISSUE TITLE
RFC 2229

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#50]
# Summary

[RFC 2229] modifies closures so that they do not capture entire variables but instead more precise paths. 

[RFC 2229]: https://github.com/rust-lang/rfcs/blob/master/text/2229-capture-disjoint-fields.md

# Info

* Lead: nikomatsakis
* Lang-team liaison: nikomatsakis
* Charter: to implement [RFC 2229]
* Repository [rust-lang/project-rfc-2229](https://github.com/rust-lang/project-rfc-2229/)
* Zulip stream `#t-compiler/wg-rfc-2229`

# What is this issue?

This issue represents an **active project group**. It is meant to be used for
the group to post updates to the lang team (and others) in a lightweight
fashion. Please do not use the comments here for discussion, that should be kept
in the Zulip stream (discussion comments here will be marked as off-topic).

**Comment by arora-aman** [comment]
There are some more relaxations to closures that can be made as side effects of work being done for 2229, proposed details can be found here: https://github.com/rust-lang/project-rfc-2229/pull/16

**Comment by nikomatsakis** [comment]
Update 2020-10-26:

Uncovered a few interesting things this far. For example, this changes behavior:

```rust
let c = || {
    let _ = x;  // today: borrows `x`
};
```

In the new edition, using the new RFC, `x` would not be captured.

**Comment by arora-aman** [comment]
- Feature mostly works and is avaiable under `#![feature(capture_disjoint_fields)]`
- We have handled all edge cases of we are aware of including patterns, FRU syntax, references in move closures, handling unsafe  
- Migration lint for drop reordering is supported under `#[deny(disjoint_capture_drop_reorder)]` and is supported using rust fix.
- On going work to support migration for auto-traits, and diagnostics

**Comment by arora-aman** [comment]
The workgroup's focus over the last month has been diagnostics, migrations and getting closer to the edition 21 release.

1. Diangostics
  - Overall improvement to closure diagnostics: we now point to part of the source code responsible for capture kind associated with the error message.
  - eg:
```rust
let mut p = Point { x: 1, y: 2 };
let y = &p.y; 
let mut c = || {  								   
       println!("{:?}", p);  								
      let x = &mut p.x;
 };
c(); 
println!("{}", y);
```

<details><summary>Ouput before change</summary>
![image](https://user-images.githubusercontent.com/4193035/118239318-9aff8400-b467-11eb-8810-72e3fe7174e4.png)
</details>

<details><summary>Ouput after change available on rust nightly</summary>
![image](https://user-images.githubusercontent.com/4193035/118239544-ec0f7800-b467-11eb-9415-90040bcba3e0.png)
</details>

2. Migrations
  - We can now detect if the closure after enabling RFC 2229 will not meet Clone or any of the auto trait bounds and provide migrations and is supported via rustfix.
  - We can annote drop implementations with `#[rustc_insignificant_dtor]`  to avoid migrating in scenarios where drop order doesn't affect semantics of the program. We intend to use to annotate stdlib to mark certain type as safe to be reorded. eg: when a string gets dropped would not affect the behavior of rest of the program.

3. Closure Size
- We wrote an initial implementation for printing out the closure size before and after the feature. The implementation is somewhat incomplete, but was good enough for us to get some data on cargo and stdlib.

Cargo and all depensices size data: https://docs.google.com/spreadsheets/d/1Irsj5O7HPPfomWat2jPTPdx_KPlsyYo5kRuQpNNuwsQ/edit?usp=sharing

**Comment by arora-aman** [comment]
- Lots of progress squelching small bugs in the implementation
- It's now part of the edition
- We are working to add material to the reference and to create a concise, formal definition of what gets captured and what doesn't (separate from the code)
- We tested the size of closures and discovered one critical optimization
- After optimization closures appear largely unchanged, but we added a useful flag (-Zprofile-closures) to measure and are going to ask people to do so

**Comment by nikomatsakis** [comment]
Stabilized!
