### ISSUE TITLE
Review "Understanding Memory and Thread Safety Practices and Issues in Real-World Rust Programs"

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#53]
# Summary

Discuss the paper [Understanding Memory and Thread Safety Practices][p] and think about what it can teach us in terms of priorities. 

[p]: https://cseweb.ucsd.edu/~yiying/RustStudy-PLDI20.pdf

# Background reading

[Paper][p]

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by Lokathor** [comment]
For those who want the "skimming it" version: [this hackmd.io](https://hackmd.io/@Lokathor/rkb09qtVP) has all the "insight" and "suggestion" entries from the paper.

**Comment by nikomatsakis** [comment]
Scheduled for Nov 18.

**Comment by nikomatsakis** [comment]
We had this meeting.

**Comment by Lokathor** [comment]
@nikomatsakis are there meeting minutes and/or notes you could link to here?

**Comment by nikomatsakis** [comment]
Good question. I do remember wanting to do some follow-ups, too, such as a lint around temporary lifetimes and side-effecting destructors (e.g., mutex guards). [Minutes are here](https://hackmd.io/O4I3P9jQQHKxwc-PqBAyFQ?view), they should be moved to the repo though. There was also [this zulip topic](https://zulip-archive.rust-lang.org/213817tlang/57100designmeetingruststudy2020langteam55.html).

**Comment by nikomatsakis** [comment]
I believe I recorded the meeting, but I don't know if I ever posted it.
