### ISSUE TITLE
Declarative macro repetition counts

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#57]
# Summary

Add new syntax to allow declarative macro authors to easily access the count or index of declarative macro repetitions.

# Info

* Lead: @markbt 
* Lang-team liaison: @lokathor
* [Charter](https://github.com/rust-lang/lang-team/blob/master/projects/declarative-macro-repetition-counts/charter.md)
* [Draft RFC](https://github.com/rust-lang/lang-team/blob/master/projects/declarative-macro-repetition-counts/0000-draft-rfc.md)
* Zulip stream `#t-lang/macro-repetition-count` on the [rust-lang Zulip](https://rust-lang.zulipchat.com/)

# What is this issue?

This issue represents an **active project group**. It is meant to be used for
the group to post updates to the lang team (and others) in a lightweight
fashion. Please do not use the comments here for discussion, that should be kept
in the Zulip stream (discussion comments here will be marked as off-topic).

**Comment by nikomatsakis** [comment]
No update this week.

**Comment by markbt** [comment]
### Project update

I've started looking at expanding more on the idea of general-purpose metavariable expressions (`${ ... }`) for use in extending the macro language, where macro repetition counts are the first user.  It's coming together pretty nicely.

For a real-world example, [this line in one of my crates](https://github.com/facebookexperimental/rust-shed/blob/master/shed/sorted_vector_map/src/map.rs#L838) would become:

    let size = ${count(value)};

There is a prototype implementation on the [markbt/rust:metavariable_expressions](https://github.com/markbt/rust/tree/metavariable_expressions) branch.  If you'd like to try it out, any feedback would be welcome.

I've started drafting an RFC on the [markbt/lang-team:metavar_expr_rfc](https://github.com/markbt/lang-team/tree/metavar_expr_rfc) branch ([Rendered](https://github.com/markbt/lang-team/blob/metavar_expr_rfc/projects/declarative-macro-repetition-counts/0000-draft-rfc.md)).  It's still in its early stages, but feedback and contributions are always welcome.

Cc: @Lokathor @rust-lang/lang

**Comment by nikomatsakis** [comment]
## Project update

* rust-lang/rfcs#3086 is posted!

**Comment by nikomatsakis** [comment]
Closing this in favor of rust-lang/rust#83527
