### ISSUE TITLE
Discuss the amount of oversight that lang should have for lints

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/lang-team#72]
# Summary

This might not need a whole meeting, but I don't know the best place to put stuff...

There seems like a bunch of different kinds of lints, and I don't know that lang should care about some of them.  For example, I think it would be fine for libs to approve a lint like "don't call `.step_by(0)` because that always panics".

We probably do care about lints that would warn on valid uses of language features (as they're sortof a deprecation).

But maybe we can write some more nuanced guidance here about which teams need to approve which things, and avoid multiple MCPs when they're not providing value.

*Please describe your meeting topic here. It doesn't have to be very long, but
it's always good to try and identify a concrete question to be answered or
narrow topic for discussion. Nobody likes a rambly meeting.*

# Background reading

This came up on https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Uplift.20the.20.60invalid_atomic_ordering.60.20lint.20from.20clippy/near/218463202

*Include any links to material that folks ought to try to read before-hand.*

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by nikomatsakis** [comment]
We're going to close this until we have a clearer idea if we need a meeting.
