### ISSUE TITLE
RFC 2229 Sync and Update

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#73]
# Summary

RFC 2229 is making progress but we're encountering some challenges that would be good to talk about.

# Background reading

* https://hackmd.io/wPs-tHJZR1Cj9j_vwsxwbw?edit

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by joshtriplett** [comment]
Scheduled for the January 20th design meeting.

**Comment by nikomatsakis** [comment]
We had this meeting! [Minutes are here](https://github.com/rust-lang/lang-team/blob/master/design-meeting-minutes/2021-01-20-RFC-2229.md)
