### ISSUE TITLE
Discuss RFC 3058, try_trait_v2

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/lang-team#75]
# Summary

[@joshtriplett mentioned on zulip](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/First.20draft.3A.20A.20new.20.60Try.60.20RFC/near/222239012) that they'd like to talk about this in a design meeting, so here's an issue for that 🙂

# Background reading

The new RFC: https://github.com/rust-lang/rfcs/pull/3058
The previous RFC: https://rust-lang.github.io/rfcs/1859-try-trait.html
The previous-previous RFC: https://rust-lang.github.io/rfcs/0243-trait-based-exception-handling.html#generalize-over-result-option-and-other-result-carrying-types
Niko's great experience report on the tracking issue: https://github.com/rust-lang/rust/issues/42327#issuecomment-366840247
Previous design meeting zulip topic: https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Design.20meeting.3A.20try.2C.20oh.20my!

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by nikomatsakis** [comment]
We had this meeting. I'm not sure if there were any minutes, but the majority was asking about the older draft of the RFC, and it has been substantially revised since then. Closing.

**Comment by scottmcm** [comment]
Not exactly meeting notes, but here's the takeaways I put in the RFC thread about the updates the RFC needed: https://github.com/rust-lang/rfcs/pull/3058#issuecomment-760328259

Those updates where then applied here: https://github.com/rust-lang/rfcs/pull/3058#issuecomment-774755749
