### ISSUE TITLE
Improving trust in the Rust compiler

### ISSUE THREAD

**Issue by skade** [rust-lang/lang-team#79]
# Summary

I would like to propose a path to improving the trust level of the Rust compiler. Trust is a function of many things: quality improvement of internals, validation of existing work and also understanding of flaws. Rust already has a lot of great base strength to start such an effort: good ties to universities, an interest in applying research and some ongoing effort in making Rust safer.

We believe it is the right moment to start making steps to climb the trust ladder. Rust is popular now and will start to see more industry adoption, also in safety-critical and mission-critical industries. Positioning Rust at a place where such concerns are to be discussed is a win, both for the industry and the project.

In this design meeting, we would like:
* To discuss a number of ongoing projects that we believe would boost this topic naturally (chalk, polonius, miri)
* Discuss the importance and chances to be found in MIR
* Discuss organisational concerns to make sure such an effort has an open roadmap and contribution possibilities

We appreciate that such an endeavor can't be discussed in one meeting. The goal of this meeting is to start working on planning and experimental work, leading to stronger discussions and maybe RFCs later, but not in a short timeframe.

# Background reading

This is based on the pitch for "Sealed Rust" last year, a name which we have now retired.
https://ferrous-systems.com/blog/sealed-rust-the-pitch/
https://ferrous-systems.com/blog/sealed-rust-the-plan/

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by RalfJung** [comment]
I'd be interested to join some of these meetings, in particular anything related to Miri or MIR semantics. :)

**Comment by skade** [comment]
@RalfJung I think for the scope of that meeting, "MIR and MIRI fit the picture well" is the level discussed on, but anything regarding sharp plans there is the scope for more focused sessions.

**Comment by nikomatsakis** [comment]
This meeting has been scheduled for Feb 17, 2021.

**Comment by nikomatsakis** [comment]
Relevant document [lang-team-proposal-trust-levels-1613584473422.pdf](https://github.com/rust-lang/lang-team/files/5997688/lang-team-proposal-trust-levels-1613584473422.pdf) and [hackmd for minutes](https://hackmd.io/wZ9lVf1JTcWAiaM7ytTvxw?edit)

**Comment by skade** [comment]
The Crux project I mentioned: https://crux.galois.com/

**Comment by nikomatsakis** [comment]
We had the meeting. Minutes here: https://github.com/rust-lang/lang-team/blob/master/design-meeting-minutes/2021-02-17-Increasing-Trust-in-Rust-Compiler.md
