### ISSUE TITLE
lang team reorg: shepherds 4.0, triage update

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#85]
# Summary

I have been working on proposed changes to update the structure of the language team. I'd like to talk them over.

# Background reading

* [Lang team reorg proposal hackmd](https://hackmd.io/7qfK5yA6Qaat_JTtXd7How)

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by nikomatsakis** [comment]
Scheduled for March 17.

**Comment by alice-i-cecile** [comment]
> lang-team design meeting proposal

This link is 404'ing for me.

**Comment by nikomatsakis** [comment]
[Minutes available here](https://github.com/rust-lang/lang-team/blob/master/design-meeting-minutes/2021-03-24-lang-team-organization.md)
