### ISSUE TITLE
Generators planning

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#92]
# Summary

Discuss possible plans around support for generators

# Background reading

*Include any links to material that folks ought to try to read before-hand.*

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by nikomatsakis** [comment]
Scheduled for April 28.

**Comment by pickfire** [comment]
Link in issue is broken.

**Comment by nikomatsakis** [comment]
Unscheduled, as the preparation didn't quite get done. =) Next time!

**Comment by nikomatsakis** [comment]
Scheduled for May 12

**Comment by nikomatsakis** [comment]
@estebank's writeup: https://hackmd.io/9v81TQSgQcaAiqvHQtzN8w?both

**Comment by nikomatsakis** [comment]
Minutes https://github.com/rust-lang/lang-team/blob/master/design-meeting-minutes/2021-05-12-Generators.md
