### ISSUE TITLE
Structural equality

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#94]
# Summary

@rust-lang/project-const-generics had a discussion about different kinds of equality. I will present a summary of the discussion and (ideally) a concrete proposal to help us unblock motion here. 

Some folks involved: @varkor, @oli-obk, @RalfJung, @lcnr (currently on a break), @chorman0773, @boxyuwu

# Background reading

Write-up - https://hackmd.io/Zrk3iPzOQDC5kOMC1B34_Q?edit

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by nikomatsakis** [comment]
Scheduled (tentatively) for 2021-07-28

@oli-obk -- let's coordinate about preparing the write-up and making sure you can attend!

**Comment by oli-obk** [comment]
I can attend

**Comment by RalfJung** [comment]
Should also work for me (assuming it's some time in the evening in Europe).

**Comment by pnkfelix** [comment]
we ended up cancelling this meeting for its previously scheduled slot. I'm removing the meeting-scheduled label so that its state will be more correctly reflected by our tools, and so that we will hopefully reschedule it at the next monthly planning meeting.

**Comment by joshtriplett** [comment]
Rescheduled, tentatively, for 2021-08-18.

**Comment by RalfJung** [comment]
What's the (tentative) time for the meeting?

The issue links to https://lang-team.rust-lang.org/design-meeting.html which I went to in hoping it would tell me, but that 404s...

**Comment by pnkfelix** [comment]
@RalfJung the standing design meeting time slot is from 7 to 8 PM CET. (The [lang team calendar](https://calendar.google.com/calendar/u/0/embed?src=recud4b9o8cmc0m5rmr033p5nk@group.calendar.google.com) has it marked with a title that says "HOLD for Lang Team Design Meeting")

**Comment by nikomatsakis** [comment]
Had this meeting! Need write-up.

**Comment by nikomatsakis** [comment]
https://github.com/rust-lang/lang-team/blob/master/design-meeting-minutes/2021-07-28-structural-equality.md
