### ISSUE TITLE
Design note catch-up

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/lang-team#95]
# Summary

Catch up on the 5 currently open design notes, and spend some time on a steady state process. Details to follow up.

* Question: Do these represent consensus?
    * These don't represent consensus around a particular design (that would be an RFC)
    * "Consensus" (or at least agreement) that they accurately represent the conversations
        * Response should just be to add
    * "Does everyone feel their points are represented?"
        * Seems excessive. We will have this discussion later.
        * Mark: I think having a lang team member look it over and say "seems all right" is good enough, they are ultimately a living document.
            * Someone can always make a PR with more.
        * Josh: my concern is that part of the point of this RFC is to to make sure positions don't get lost by the time an RFC comes up
            * We've sometimes had years pass.
    * Niko: Let's document the purpose ("these aim to capture design points, considerations, and don't represent consensus around a particular design")
        * and then assign to a person to merge when they feel ready
    * Mark: some of these have been open since Oct 2020!
        * having them get merged quickly will be more beneficial than having them sit around
    * Josh: may make sense to spend a bit of time in meeting
    * Mark: Scratch proposal:
        * I would file an issue to use a design meeting and spend some time this month to catch up
    * Josh: I do see value in having a lang team member to review it (also not the author)
    * Rough consensus:
        * Steady state process is to assign a reviewer

### "Initial draft of copy ergonomics design note" lang-team#62

**Link:** https://github.com/rust-lang/lang-team/pull/62

### "Autoref/autoderef for operators" lang-team#63

**Link:** https://github.com/rust-lang/lang-team/pull/63

### "Auto trait design note" lang-team#69

**Link:** https://github.com/rust-lang/lang-team/pull/69

### "Add design notes for function-type `Default` implementation discussion" lang-team#71

**Link:** https://github.com/rust-lang/lang-team/pull/71

### "Add draft of variadic notes" lang-team#76

**Link:** https://github.com/rust-lang/lang-team/pull/76

# Background reading

TBD

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by nikomatsakis** [comment]
We did this in today's planning meeting.
