### ISSUE TITLE
negative impls integrated into coherence

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#96]
# Proposal

## Summary and problem statement

@yaahc and I have been investigating the possibility of integrating 'negative impls' into coherence. The precise motivation is to enable

```rust
impl !Error for &str { }
```

and then, in a downstream crate, support

```rust
impl From<&str> for Box<dyn Error>> { }
impl<E> From<E> for Box<dyn Error>>
where
    E: Error, { }
```

Note that this would not permit `where T: !Trait` syntax, although we could in principle support that, though we would have to be careful about what it means (in particular, it would be relatively easy to support if what it means is "there is a negative impl").

## Motivation, use-cases, and solution sketches

* Supporting the project group's work, as described above

## Prioritization

Fits under error handling, and is also a kind of core enabler likely to arise elsewhere

[lang team priorities]: https://lang-team.rust-lang.org/priorities.html

## Links and related work

* Tracking isssue for negative impls https://github.com/rust-lang/rust/issues/68318
* Implementation of negative impls https://github.com/rust-lang/rust/pull/68004
* Interactions with marker traits and overlapping impls https://github.com/rust-lang/rust/issues/29864

## Initial people involved

nikomatsakis, yaahc

## What happens now?

This issue is part of the experimental MCP process described in [RFC 2936]. Once this issue is filed, a Zulip topic will be opened for discussion, and the lang-team will review open MCPs in its weekly triage meetings. You should receive feedback within a week or two.

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/lang/mcp.html
[forge]: https://forge.rust-lang.org/
[RFC 2936]: https://github.com/rust-lang/rfcs/pull/2936/

**Comment by scottmcm** [comment]
This sounds great!

Related to the !Error for `str`, it would be cool if this also let us `impl !FnOnce for str`, instead of needing this `#[fundamental]`:
https://github.com/rust-lang/rust/blob/7f9ab0300cd66f6f616e03ea90b2d71af474bf28/library/core/src/ops/function.rs#L65-L67

**Comment by nikomatsakis** [comment]
Ah, interesting, I hadn't considered the idea that we might use it to remove *some* fundamental, even if we can't remove them all. Yes, that would be good.

**Comment by scottmcm** [comment]
I don't know if this works or is needed here, but let's find out

@rustbot second

**Comment by nikomatsakis** [comment]
We agreed to let this work proceed. I will create the relevant tracking issue.

**Comment by nikomatsakis** [comment]
However, I'd like to discuss this as part of tomorrow's planning meeting. We would need a liaison, I think, and I'm not sure that @yaahc can realistically be the owner here (I think it is realistically me).

**Comment by pnkfelix** [comment]
(I'm willing to be liason. We should revisit official assignment of liason in future lang team meeting; today's only has two team members present.)

**Comment by yoshuawuyts** [comment]
As an experiment I implemented `async fn main` in the compiler using this feature ([branch](https://github.com/yoshuawuyts/rust/tree/future-for-termination-2)). This uses the following negative trait bounds to allow us to `impl Termination for Future<T>`:

```rust
impl !Future for ! {}
impl !Future for () {}
impl<E: ?Sized> !Future for Result<!, E> {}
impl<E: ?Sized> !Future for Result<(), E> {}
```

There was figuring out to do regarding `dyn` traits which might need to be improved; but overall this feature has been incredibly useful and is a missing piece to enable `async fn main` to be implemented.

**Comment by nikomatsakis** [comment]
This is basically all set but we just need to create the real tracking issue. @pnkfelix will serve as liaison. There is a repository here for those interested in more details:

https://rust-lang.github.io/negative-impls-initiative/

**Comment by yaahc** [comment]
> This is basically all set but we just need to create the real tracking issue. @pnkfelix will serve as liaison. There is a repository here for those interested in more details:
> 
> https://rust-lang.github.io/negative-impls-initiative/

I couldn't find a link to the repo in the mdbook you linked but was able to guess it from the url: https://github.com/rust-lang/negative-impls-initiative

**Comment by nikomatsakis** [comment]
Closing in favor of https://github.com/rust-lang/lang-team/issues/136
