### ISSUE TITLE
Trait upcasting coercion

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/lang-team#98]
# Proposal

## Summary and problem statement

* Add the `trait_upcasting` feature to the language.

## Motivation, use-cases, and solution sketches

* The `trait_upcasting` feature adds support for trait upcasting coercion. This allows a
trait object of type `dyn Bar` to be cast to a trait object of type `dyn Foo`
so long as `Bar: Foo`.

```rust,edition2018
#![feature(trait_upcasting)]

trait Foo {}

trait Bar: Foo {}

impl Foo for i32 {}

impl<T: Foo + ?Sized> Bar for T {}

let foo: &dyn Foo = &123;
let bar: &dyn Bar = foo;
```

## Prioritization

* This belongs to the "Trait and type system extensions" part of the [lang team priorities].

[lang team priorities]: https://lang-team.rust-lang.org/priorities.html

## Links and related work

* Previously established tracking issue: https://github.com/rust-lang/rust/issues/65991

## Initial people involved

* @crlf0710
* @nikomatsakis 

Also cc @alexreg and @eddyb in case they're interested.

## What happens now?

This issue is part of the experimental MCP process described in [RFC 2936]. Once this issue is filed, a Zulip topic will be opened for discussion, and the lang-team will review open MCPs in its weekly triage meetings. You should receive feedback within a week or two.

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/lang/mcp.html
[forge]: https://forge.rust-lang.org/
[RFC 2936]: https://github.com/rust-lang/rfcs/pull/2936/

**Comment by pnkfelix** [comment]
This presentation has some typos. (E.g. the roles of `Foo` and `Bar` switch inexplicably.)

More importantly, I think it would benefit from spelling out a few more cases. E.g. a trait can have multiple super-traits. I assume upcasts will be supported even in that case.

**Comment by nikomatsakis** [comment]
This has been seconded and the https://rust-lang.github.io/dyn-upcasting-coercion-initiative/ repository created to track this work!

**Comment by JeremyRubin** [comment]
the example seems backwards? should it not be:
```rust
#![feature(trait_upcasting)]

trait Foo {}

trait Bar: Foo {}

impl Foo for i32 {}

impl<T: Foo + ?Sized> Bar for T {}

let foo: &dyn Bar = &123;
let bar: &dyn Foo = foo;
```

where Bar is able to cast up to Foo, as described "trait object of type dyn Bar to be cast to a trait object of type dyn Foo
so long as Bar: Foo.".

Of course, both directions could be possible, but it seems reversed here.

**Comment by vityafx** [comment]
Is there a workaround until this becomes available?

**Comment by JeremyRubin** [comment]
yes, i *think* casting through a struct should work?

```rust

struct CastFoo<'a>(&'a dyn Bar);

impl<'a> Foo for CastFoo<'a> {
  fn fo_every_foo_method(&self, a:Param) -> Output {
    self.0.that_method(a)
  }
}

let bar: &dyn Bar = &123;
let tmp = CastFoo(bar);
let foo: &dyn Foo = &tmp;

```

**Comment by vityafx** [comment]
> 

I guess I am doing almost exactly that now. But this code is so ugly that by "workaround" I meant something else :-) Thanks anyway.

**Comment by edevil** [comment]
Is there some way to help regarding stabilising this feature?
